name: Synthetic backfill (one-shot, historical)

on:
  workflow_dispatch:
    inputs:
      start_date:
        description: "Start date (YYYY-MM-DD, inclusive, UTC)"
        required: true
        type: string
      end_date:
        description: "End date (YYYY-MM-DD, inclusive, UTC)"
        required: true
        type: string
      persona_pool:
        description: "Persona pool size"
        required: true
        default: "400"
        type: string

jobs:
  backfill:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm i posthog-node

      - name: Restore persona state
        uses: actions/cache@v4
        with:
          path: .synthetic_state
          key: personas-shared-v1

      - name: Run backfill
        run: node scripts/backfill/backfill.js
        env:
          PH_PROJECT_API_KEY: ${{ secrets.PH_PROJECT_API_KEY }}
          PH_HOST: ${{ secrets.PH_HOST }}
          STATE_DIR: .synthetic_state
          START_DATE: ${{ inputs.start_date }}
          END_DATE: ${{ inputs.end_date }}
          PERSONA_POOL: ${{ inputs.persona_pool }}
